[game]
# The name of the crate in the current workspace that implements the game entry point
crate_name = "aleph-test"

# The name of the game, as should appear as a pretty string like an app title
name = "Aleph Test"

# The name of the publisher/author of the game.
author = "Nathan Voglsam"

# The list of allowed platforms that the game is designed to target
# Current possible values: "windows", "macos", "linux"
target_platforms = ["windows", "macos", "linux"]

# Specification of app branding for Windows
[windows.branding]
icon = "game/branding/windows/app_icon.ico"
