jobs:
  - job: Windows
    pool:
      vmImage: "windows-latest"
    steps:
      - template: "ci/rust-ci.yml"
        parameters:
          setupSteps:
            - powershell: |
                choco install ninja
              displayName: Install Binary Dependencies
  - job: Linux
    pool:
      vmImage: "ubuntu-20.04"
    steps:
      - template: "ci/rust-ci.yml"
        parameters:
          setupSteps:
            - powershell: |
                sudo apt -y update -qq
                sudo apt -y install -qq wget cmake libgtk-3-dev libsdl2-dev ninja-build libx11-dev libxext-dev libpulse-dev libasound2-dev curl p7zip-full p7zip-rar
              displayName: Install Dependencies
