# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Cargo@1
  displayName: Build
  inputs:
    cargoCommand: 'build --release'
    verbose: false
- task: Cargo@1
  displayName: Test
  inputs:
    cargoCommand: 'test --release'
    verbose: false
