##
##
## This file is a part of Aleph
##
## https://github.com/nathanvoglsam/aleph
##
## MIT License
##
## Copyright (c) 2020 Aleph Engine
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all
## copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.
##

## Uncomment on an absolute final release build to maximize the compiler's optimization ability
##[profile.release]
##lto = "fat"
##panic = 'unwind'
##codegen-units = 1

[workspace]

members = [
    "engine/aleph-app-info",
    "engine/aleph-cpu-info",
    "engine/aleph-embedded-data",
    "engine/aleph-engine",
    "engine/aleph-math",
    "engine/aleph-platform",
    "engine/aleph-platform-imgui",
    "engine/aleph-settings",
    "utils/aleph-compile",
    "utils/aleph-imgui",
    "utils/aleph-ktx",
    "utils/aleph-log",
    "utils/aleph-logger",
    "utils/aleph-macros",
    "utils/aleph-target",
    "utils/aleph-target-build",
    "utils/aleph-vk-format",
    "graphics/aleph-render",
    "graphics/aleph-render-graph",
    "graphics/aleph-vulkan",
    "graphics/aleph-vulkan-alloc",
    "graphics/aleph-vulkan-alloc-sys",
    "graphics/aleph-vulkan-core",
    "game/aleph-test",
]
