##
##
## This file is a part of Aleph
##
## https://github.com/nathanvoglsam/aleph
##
## MIT License
##
## Copyright (c) 2020 Aleph Engine
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all
## copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.
##

## Uncomment on an absolute final release build to maximize the compiler's optimization ability
##[profile.release]
##lto = "fat"
##panic = 'unwind'
##codegen-units = 1

[workspace]

resolver = "2"

members = [
    "lib/crates/aleph-any",
    "lib/crates/aleph-compile",
    "lib/crates/aleph-console",
    "lib/crates/aleph-combine-utils",
    "lib/crates/aleph-dx12",
    "lib/crates/aleph-dx12-alloc",
    "lib/crates/aleph-dx12-alloc-raw",
    "lib/crates/aleph-ecs",
    "lib/crates/aleph-engine",
    "lib/crates/aleph-gpu",
    "lib/crates/aleph-interfaces",
    "lib/crates/aleph-ktx",
    "lib/crates/aleph-label",
    "lib/crates/aleph-log",
    "lib/crates/aleph-pix",
    "lib/crates/aleph-pix-raw",
    "lib/crates/aleph-schema",
    "lib/crates/aleph-sexpr",
    "lib/crates/aleph-sys-info",
    "lib/crates/aleph-target",
    "lib/crates/aleph-target-build",
    "lib/crates/aleph-virtual-buffer",
    "lib/crates/aleph-vk-format",
    "lib/crates/aleph-vulkan",
    "lib/crates/aleph-vulkan-alloc",
    "lib/crates/aleph-vulkan-alloc-sys",
    "lib/crates/aleph-vulkan-core",
    "lib/crates/aleph-windows",
    "lib/plugins/aleph-core",
    "lib/plugins/aleph-egui",
    "lib/plugins/aleph-gpu-dx12",
    "lib/plugins/aleph-gpu-vulkan",
    "lib/plugins/aleph-headless",
    "lib/plugins/aleph-render",
    "lib/plugins/aleph-sdl2",
    "bin/aleph-test",
    "bin/aleph-rcon",
]
