##
##
## This file is a part of Aleph
##
## https://github.com/nathanvoglsam/aleph
##
## MIT License
##
## Copyright (c) 2020 Aleph Engine
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all
## copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.
##

## Uncomment on an absolute final release build to maximize the compiler's optimization ability
##[profile.release]
##lto = "fat"
##panic = 'unwind'
##codegen-units = 1

[workspace]

members = [
    "crates/build/aleph-compile",
    "crates/build/aleph-target",
    "crates/build/aleph-target-build",
    "crates/engine/aleph-any",
    "crates/engine/aleph-engine",
    "crates/engine/aleph-interfaces",
    "crates/engine/plugins/aleph-egui",
    "crates/engine/plugins/aleph-headless",
    "crates/engine/plugins/aleph-render",
    "crates/engine/plugins/aleph-sdl2",
    "crates/engine/aleph-plugin-registry",
    "crates/graphics/aleph-dx12",
    "crates/graphics/aleph-dx12-alloc",
    "crates/graphics/aleph-dxc",
    "crates/graphics/aleph-pix",
    "crates/ktx/aleph-ktx",
    "crates/ktx/aleph-vk-format",
    "crates/logging/aleph-log",
    "crates/logging/aleph-logger",
    "crates/raw/aleph-dx12-alloc-raw",
    "crates/raw/aleph-dxc-raw",
    "crates/raw/aleph-pix-raw",
    "crates/raw/aleph-windows-raw",
    "game/aleph-test",
]
