##
##
## This file is a part of Aleph
##
## <ALEPH_REPO_REPLACE>
##
## <ALEPH_LICENSE_REPLACE>
##

[workspace]

members = [
    "aleph-app-info",
    "aleph-compile",
    "aleph-embedded-data",
    "aleph-engine",
    "aleph-macros",
    "aleph-math",
    "aleph-target",
    "aleph-target-crate",
    "aleph-test",
    "aleph-vma-sys",
    "aleph-vulkan",
    "aleph-vulkan-alloc",
    "aleph-vulkan-core",
]
