##
##
## This file is a part of Aleph
##
## <ALEPH_REPO_REPLACE>
##
## <ALEPH_LICENSE_REPLACE>
##

[workspace]

members = [
    "aleph-compile",
    "aleph-engine",
    "aleph-math",
    "aleph-target",
    "aleph-target-crate",
    "aleph-test",
]
