##
##
## This file is a part of Aleph
##
## <ALEPH_REPO_REPLACE>
##
## <ALEPH_LICENSE_REPLACE>
##

## Uncomment on an absolute final release build to maximize the compiler's optimization ability
##[profile.release]
##lto = "fat"
##panic = 'unwind'
##codegen-units = 1

[workspace]

members = [
    "engine/aleph-app-info",
    "engine/aleph-cpu-info",
    "engine/aleph-embedded-data",
    "engine/aleph-engine",
    "engine/aleph-math",
    "engine/aleph-platform",
    "engine/aleph-platform-imgui",
    "engine/aleph-settings",
    "utils/aleph-compile",
    "utils/aleph-imgui",
    "utils/aleph-ktx",
    "utils/aleph-log",
    "utils/aleph-logger",
    "utils/aleph-macros",
    "utils/aleph-target",
    "utils/aleph-target-build",
    "utils/aleph-vk-format",
    "graphics/aleph-render",
    "graphics/aleph-render-graph",
    "graphics/aleph-vulkan",
    "graphics/aleph-vulkan-alloc",
    "graphics/aleph-vulkan-alloc-sys",
    "graphics/aleph-vulkan-core",
    "game/aleph-test",
]
