##
##
## This file is a part of Aleph
##
## https://github.com/nathanvoglsam/aleph
##
## MIT License
##
## Copyright (c) 2020 Aleph Engine
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all
## copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.
##

## Uncomment on an absolute final release build to maximize the compiler's optimization ability
##[profile.release]
##lto = "fat"
##panic = 'unwind'
##codegen-units = 1

[workspace]

resolver = "2"

members = [
    "lib/archived/aleph-combine-utils",
    "lib/archived/aleph-ktx",
    "lib/archived/aleph-schema",
    "lib/archived/aleph-sexpr",
    "lib/archived/aleph-vk-format",
    "lib/crates/aleph-any",
    "lib/crates/aleph-compile",
    "lib/crates/aleph-console",
    "lib/crates/aleph-dx12-agility-sdk",
    "lib/crates/aleph-dx12-alloc",
    "lib/crates/aleph-ecs",
    "lib/crates/aleph-engine",
    "lib/crates/aleph-gpu",
    "lib/crates/aleph-interfaces",
    "lib/crates/aleph-label",
    "lib/crates/aleph-pix",
    "lib/crates/aleph-pix-raw",
    "lib/crates/aleph-rhi-api",
    "lib/crates/aleph-rhi-dx12",
    "lib/crates/aleph-rhi-impl-utils",
    "lib/crates/aleph-rhi-loader",
    "lib/crates/aleph-rhi-loader-api",
    "lib/crates/aleph-rhi-validation",
    "lib/crates/aleph-rhi-vulkan",
    "lib/crates/aleph-sys-info",
    "lib/crates/aleph-target",
    "lib/crates/aleph-target-build",
    "lib/crates/aleph-virtual-buffer",
    "lib/crates/aleph-vulkan-alloc",
    "lib/crates/aleph-windows",
    "lib/plugins/aleph-core",
    "lib/plugins/aleph-egui",
    "lib/plugins/aleph-headless",
    "lib/plugins/aleph-render",
    "lib/plugins/aleph-rhi",
    "lib/plugins/aleph-sdl2",
    "bin/aleph-test",
    "bin/aleph-rcon",
]

[workspace.dependencies]
once_cell = "1"
crossbeam = "0.8"
parking_lot = "0.12"
bitflags = "1"
thiserror = "1"
anyhow = "1"
raw-window-handle = "0.4"
env_logger = "0.9"
utf16_lit = "2"
libc = "0.2"
cstr = "0.2"
ash = "0.37"
erupt = "0.22"
log = { version = "0.4", features = ["release_max_level_info"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
bumpalo = { version = "3", features = ["boxed", "collections"] }
cc = "1"
libloading = "0.7"

aleph-any = { path = "./lib/crates/aleph-any", version = "0.1" }
aleph-compile = { path = "./lib/crates/aleph-compile", version = "1" }
aleph-interfaces = { path = "./lib/crates/aleph-interfaces", version = "0.1" }
aleph-rhi-api = { path = "./lib/crates/aleph-rhi-api", version = "0.1" }
aleph-rhi-loader-api = { path = "./lib/crates/aleph-rhi-loader-api", version = "0.1" }
aleph-target = { path = "./lib/crates/aleph-target", version = "2" }
aleph-target-build = { path = "./lib/crates/aleph-target-build", version = "2" }
aleph-windows = { path = "./lib/crates/aleph-windows", version = "0.1" }
