##
##
## This file is a part of Aleph
##
## <ALEPH_REPO_REPLACE>
##
## <ALEPH_LICENSE_REPLACE>
##

[workspace]

members = [
    "engine/aleph-app-info",
    "engine/aleph-cpu-info",
    "engine/aleph-embedded-data",
    "engine/aleph-engine",
    "engine/aleph-logger",
    "engine/aleph-math",
    "engine/aleph-platform",
    "engine/aleph-settings",
    "utils/aleph-compile",
    "utils/aleph-macros",
    "utils/aleph-target",
    "utils/aleph-target-crate",
    "graphics/aleph-vulkan",
    "graphics/aleph-vulkan-alloc",
    "graphics/aleph-vulkan-alloc-sys",
    "graphics/aleph-vulkan-core",
    "game/aleph-test",
]
