cp ".\target\x86_64-uwp-windows-msvc\debug\aleph_test.pdb" "..\aleph_appx\aleph_test.pdb"
cp ".\target\x86_64-uwp-windows-msvc\debug\aleph-test.exe" "..\aleph_appx\aleph-test.exe"
cp ".\target\x86_64-uwp-windows-msvc\debug\SDL2.pdb" "..\aleph_appx\SDL2.pdb"
cp ".\target\x86_64-uwp-windows-msvc\debug\SDL2.dll" "..\aleph_appx\SDL2.dll"
cp ".\target\x86_64-uwp-windows-msvc\debug\WinPixEventRuntime_UAP.dll" "..\aleph_appx\WinPixEventRuntime_UAP.dll"