#![allow(unused_variables, non_upper_case_globals, non_snake_case)]
#[allow(unused_variables, non_upper_case_globals, non_snake_case)]
pub mod com;
#[allow(unused_variables, non_upper_case_globals, non_snake_case)]
pub mod direct3d11;
#[allow(unused_variables, non_upper_case_globals, non_snake_case)]
pub mod direct3d12;
#[allow(unused_variables, non_upper_case_globals, non_snake_case)]
pub mod display_devices;
#[allow(unused_variables, non_upper_case_globals, non_snake_case)]
pub mod dxgi;
#[allow(unused_variables, non_upper_case_globals, non_snake_case)]
pub mod gdi;
#[allow(unused_variables, non_upper_case_globals, non_snake_case)]
pub mod kernel;
#[allow(unused_variables, non_upper_case_globals, non_snake_case)]
pub mod structured_storage;
#[allow(unused_variables, non_upper_case_globals, non_snake_case)]
pub mod system_services;
#[allow(unused_variables, non_upper_case_globals, non_snake_case)]
pub mod windows_and_messaging;
#[allow(unused_variables, non_upper_case_globals, non_snake_case)]
pub mod windows_programming;
#[allow(unused_variables, non_upper_case_globals, non_snake_case)]
pub mod winrt;
