##
##
## This file is a part of Aleph
##
## https://github.com/nathanvoglsam/aleph
##
## MIT License
##
## Copyright (c) 2020 Aleph Engine
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all
## copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.
##


[package]
name = "aleph-platform-sdl2"
version = "0.1.0"
authors = ["Nathan Voglsam <nathanvoglsam420@gmail.com>"]
description = "The windowing and input implementation for aleph, based on SDL2"
license = "MIT"
repository = "https://github.com/nathanvoglsam/aleph"
documentation = "https://docs.rs/aleph-platform-sdl2/"
readme = "README.md"
## TODO: keywords = ["macro", "utility"]
## TODO: categories = ["development-tools::build-utils"]
edition = "2018"

[dependencies]
aleph-app-info = { path = "../../config/aleph-app-info", version = "0.1" }
aleph-log = { path = "../../logging/aleph-log", version = "1" }
aleph-settings = { path = "../../config/aleph-settings", version = "0.1" }
aleph-interfaces = { path = "../../engine/aleph-interfaces", version = "0.1" }
once_cell = "1"
parking_lot = "0.10"

[dependencies.sdl2]
git = "https://github.com/nathanvoglsam/rust-sdl2.git"
branch = "custom-raw-window-fork"
version = "0.34"
features = ["raw-window-handle"]

[dependencies.raw-window-handle]
git = "https://github.com/rust-windowing/raw-window-handle.git"
branch = "master"
version = "0.3"

[build-dependencies]
cmake = "0.1"
aleph-compile = { path = "../../build/aleph-compile", version = "1" }
aleph-target-build = { path = "../../build/aleph-target-build", version = "2" }

[badges]
azure-devops = { project = "nathanvoglsam420/Aleph", pipeline = "nathanvoglsam.aleph", build = "1" }
