//
//
// This file is a part of Aleph
//
// https://github.com/nathanvoglsam/aleph
//
// MIT License
//
// Copyright (c) 2020 Aleph Engine
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//

mod closure_pass;
mod pass_index;

pub use closure_pass::ClosurePass;
pub use pass_index::PassIndex;

use crate::RenderGraphBuilder;
use crate::ResourceAccess;
use std::collections::HashSet;

///
/// The trait that specifies the required interface for a render graph node
///
pub trait RenderGraphPass {
    ///
    /// Function called while building the graph for registering resource accesses by this pass.
    ///
    fn register_access(&mut self, accesses: &mut ResourceAccess);

    ///
    /// This will be called during render graph construction, after concrete resources have been
    /// created to allow for the pass to compile any objects that need to refer to resources
    /// generated by the graph, such as for compiling pipeline state objects, render passes, frame
    /// buffers, etc.
    ///
    fn compile(&mut self);

    ///
    /// Record the commands for this pass onto a command buffer. Appropriate barriers will be
    /// already be recorded into the command buffer.
    ///
    fn record(&mut self);
}

///
/// Internal struct for representing the execution dependencies between passes
///
pub(crate) struct GraphLink {
    pub depends_on: HashSet<PassIndex>,
    pub waited_on_by: HashSet<PassIndex>,
}

///
/// A built render graph
///
pub struct RenderGraph<'a> {
    ///
    /// Storage for the actual pass objects
    ///
    pub(crate) passes: Vec<Box<dyn RenderGraphPass + 'a>>,

    ///
    /// Holds the execution dependencies for a pass.
    ///
    pub(crate) links: Vec<GraphLink>,

    ///
    /// The set of resources read to and written by each pass,
    ///
    pub(crate) accesses: Vec<ResourceAccess>,
}

impl<'a> RenderGraph<'a> {
    ///
    /// Returns a new builder instance
    ///
    pub fn builder() -> RenderGraphBuilder<'a> {
        RenderGraphBuilder::new()
    }
}
