##
##
## This file is a part of Aleph
##
## https://github.com/nathanvoglsam/aleph
##
## MIT License
##
## Copyright (c) 2020 Aleph Engine
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all
## copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.
##


[package]
name = "aleph-engine"
version = "0.1.0"
authors = ["Nathan Voglsam <nathanvoglsam420@gmail.com>"]
description = "A Rust and Vulkan powered 3D game engine"
license = "MIT"
repository = "https://github.com/nathanvoglsam/aleph"
documentation = "https://docs.rs/aleph-engine/"
readme = "README.md"
keywords = ["engine", "graphics", "vulkan", "game"]
categories = ["game-engines"]
edition = "2018"

[badges]
azure-devops = { project = "nathanvoglsam420/Aleph", pipeline = "nathanvoglsam.aleph", build = "1" }

[dependencies]
aleph-app-info = { path = "../../config/aleph-app-info", version = "0.1.0" }
aleph-cpu-info = { path = "../../platform/aleph-cpu-info", version = "1.0.0" }
aleph-log = { path = "../../logging/aleph-log", version = "1.0.0" }
aleph-logger = { path = "../../logging/aleph-logger", version = "0.1.0" }
aleph-platform = { path = "../../platform/aleph-platform", version = "0.1.0" }
aleph-platform-imgui = { path = "../../platform/aleph-platform-imgui", version = "0.1.0" }
aleph-settings = { path = "../../config/aleph-settings", version = "0.1.0" }
aleph-render = { path = "../../graphics/aleph-render", version = "0.1.0" }
aleph-target = { path = "../../build/aleph-target", version = "2.0.0" }
aleph-vulkan = { path = "../../graphics/aleph-vulkan", version = "0.1.0" }
aleph-vulkan-core = { path = "../../graphics/aleph-vulkan-core", version = "0.1.0" }
aleph-vulkan-alloc = { path = "../../graphics/aleph-vulkan-alloc", version = "0.1.0" }
imgui = "0.4.0"
clap = "2.33"
rayon = "1.3"
once_cell = "1.4"
optick = { git = "https://github.com/nathanvoglsam/optick-rs.git", branch = "remove-bundled-libs" }
